spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 190028478423-s2jc2ruii8nalg6kij1lh4jbfi1b8p04.apps.googleusercontent.com
            clientSecret: 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
          github:
            clientId: 190028478423-s2jc2ruii8nalg6kij1lh4jbfi1b8p04.apps.googleusercontent.com
            clientSecret: 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
          facebook:
            clientId: 190028478423-s2jc2ruii8nalg6kij1lh4jbfi1b8p04.apps.googleusercontent.com
            clientSecret: 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
